NOTE: Redirects are currently not supported in Windows or MacOs.
/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/Users/liangming.xu/code/UniAD/./tools/test.py", line 14, in <module>
Traceback (most recent call last):
  File "/Users/liangming.xu/code/UniAD/./tools/test.py", line 14, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/Users/liangming.xu/code/mmdetection3d/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
    from mmdet3d.apis import single_gpu_test
  File "/Users/liangming.xu/code/mmdetection3d/mmdet3d/__init__.py", line 21, in <module>
Traceback (most recent call last):
  File "/Users/liangming.xu/code/UniAD/./tools/test.py", line 14, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
    from mmdet3d.apis import single_gpu_test
  File "/Users/liangming.xu/code/mmdetection3d/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
Traceback (most recent call last):
  File "/Users/liangming.xu/code/UniAD/./tools/test.py", line 14, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/Users/liangming.xu/code/mmdetection3d/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
Traceback (most recent call last):
  File "/Users/liangming.xu/code/UniAD/./tools/test.py", line 14, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/Users/liangming.xu/code/mmdetection3d/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
Traceback (most recent call last):
  File "/Users/liangming.xu/code/UniAD/./tools/test.py", line 14, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/Users/liangming.xu/code/mmdetection3d/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
Traceback (most recent call last):
  File "/Users/liangming.xu/code/UniAD/./tools/test.py", line 14, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/Users/liangming.xu/code/mmdetection3d/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
Traceback (most recent call last):
  File "/Users/liangming.xu/code/UniAD/./tools/test.py", line 14, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/Users/liangming.xu/code/mmdetection3d/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26533) of binary: /opt/homebrew/anaconda3/envs/laneaf/bin/python
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/homebrew/anaconda3/envs/laneaf/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-29_14:51:47
  host      : MBYLJYT6J537.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 26534)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-06-29_14:51:47
  host      : MBYLJYT6J537.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 26535)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-06-29_14:51:47
  host      : MBYLJYT6J537.local
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 26536)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-06-29_14:51:47
  host      : MBYLJYT6J537.local
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 26537)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-06-29_14:51:47
  host      : MBYLJYT6J537.local
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 26538)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-06-29_14:51:47
  host      : MBYLJYT6J537.local
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 26539)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-06-29_14:51:47
  host      : MBYLJYT6J537.local
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 26540)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-29_14:51:47
  host      : MBYLJYT6J537.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26533)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
